services:
  api:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - db
    env_file:
      - .env
    restart: always

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    volumes:
      - ./database/migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://postgres:oserafim@db:5432/elephrases?sslmode=disable", "up"]
    depends_on:
      - db

volumes:
  db_data:
