ALTER TABLE flashcards
ADD COLUMN next_review_at TIMESTAMP,
ADD COLUMN state VARCHAR(255) DEFAULT 'new' NOT NULL,
ADD COLUMN interval BIGINT DEFAULT 0 NOT NULL,
ADD COLUMN ease_factor FLOAT DEFAULT 2.5 NOT NULL;